
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 06:00:50 KST (Jul  8 2026 21:00:50 UTC)

// Verification Directory fv/ls194 

module ls194(clk, rst_n, i_sel, i_pd, i_ls, i_rs, o_q);
  input clk, rst_n, i_ls, i_rs;
  input [1:0] i_sel;
  input [3:0] i_pd;
  output [3:0] o_q;
  wire clk, rst_n, i_ls, i_rs;
  wire [1:0] i_sel;
  wire [3:0] i_pd;
  wire [3:0] o_q;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19;
  DFFRHQX1 \o_q_reg[0] (.RN (rst_n), .CK (clk), .D (n_15), .Q (o_q[0]));
  DFFRHQX1 \o_q_reg[1] (.RN (rst_n), .CK (clk), .D (n_18), .Q (o_q[1]));
  DFFRHQX1 \o_q_reg[3] (.RN (rst_n), .CK (clk), .D (n_16), .Q (o_q[3]));
  DFFRHQX1 \o_q_reg[2] (.RN (rst_n), .CK (clk), .D (n_19), .Q (o_q[2]));
  OAI211X1 g389__2398(.A0 (n_3), .A1 (n_17), .B0 (n_7), .C0 (n_11), .Y
       (n_19));
  OAI211X1 g392__5107(.A0 (n_1), .A1 (n_17), .B0 (n_4), .C0 (n_14), .Y
       (n_18));
  OAI211X1 g390__6260(.A0 (n_0), .A1 (n_17), .B0 (n_6), .C0 (n_9), .Y
       (n_16));
  OAI211X1 g391__4319(.A0 (n_2), .A1 (n_17), .B0 (n_5), .C0 (n_13), .Y
       (n_15));
  AOI22X1 g393__8428(.A0 (n_12), .A1 (o_q[1]), .B0 (n_10), .B1
       (o_q[2]), .Y (n_14));
  AOI22X1 g394__5526(.A0 (n_12), .A1 (o_q[0]), .B0 (i_ls), .B1 (n_8),
       .Y (n_13));
  AOI22X1 g395__6783(.A0 (n_12), .A1 (o_q[2]), .B0 (n_10), .B1
       (o_q[3]), .Y (n_11));
  AOI22X1 g396__3680(.A0 (n_12), .A1 (o_q[3]), .B0 (n_8), .B1 (o_q[2]),
       .Y (n_9));
  NAND2XL g397__1617(.A (n_8), .B (o_q[1]), .Y (n_7));
  NAND2XL g398__2802(.A (i_rs), .B (n_10), .Y (n_6));
  NAND2XL g399__1705(.A (n_10), .B (o_q[1]), .Y (n_5));
  NAND2X1 g400__5122(.A (n_8), .B (o_q[0]), .Y (n_4));
  NAND2XL g401__8246(.A (i_sel[0]), .B (i_sel[1]), .Y (n_17));
  NOR2BX1 g402__7098(.AN (i_sel[0]), .B (i_sel[1]), .Y (n_10));
  NOR2XL g403__6131(.A (i_sel[0]), .B (i_sel[1]), .Y (n_12));
  NOR2BX1 g404__1881(.AN (i_sel[1]), .B (i_sel[0]), .Y (n_8));
  INVXL g406(.A (i_pd[2]), .Y (n_3));
  INVXL g408(.A (i_pd[0]), .Y (n_2));
  INVXL g405(.A (i_pd[1]), .Y (n_1));
  INVXL g407(.A (i_pd[3]), .Y (n_0));
endmodule

