
// Generated by Cadence Genus(TM) Synthesis Solution 22.17-s071_1
// Generated on: Jul  9 2026 00:11:34 KST (Jul  8 2026 15:11:34 UTC)

// Verification Directory fv/GPIO_MUX 

module GPIO_MUX(i_sel, i_tx0, i_rx0, i_pwm1, i_peri0, o_gpio_pin);
  input [1:0] i_sel;
  input i_tx0, i_rx0, i_pwm1, i_peri0;
  output o_gpio_pin;
  wire [1:0] i_sel;
  wire i_tx0, i_rx0, i_pwm1, i_peri0;
  wire o_gpio_pin;
  MX4XL g90__2398(.A (i_tx0), .B (i_pwm1), .C (i_rx0), .D (i_peri0),
       .S0 (i_sel[1]), .S1 (i_sel[0]), .Y (o_gpio_pin));
endmodule

